[package]
name = "invensense_mpu"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[dependencies]
periphery_core = {path = "../../periphery_core/" }
packed_struct = "^0.1.0"
packed_struct_codegen = "^0.1.0"

[lib]
name = "invensense_mpu"
path = "lib.rs"
